// <auto-generated />
using System;
using ControleDeDividas.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleDeDividas.Infra.Migrations
{
    [DbContext(typeof(SystemContext))]
    partial class SystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ControleDeDividas.Domain.Models.Divida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CpfDoDevedor")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<decimal>("Juros")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Multa")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("NomeDoDevedor")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroDoTitulo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Dividas", (string)null);
                });

            modelBuilder.Entity("ControleDeDividas.Domain.Models.Parcela", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataDeVencimento")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DividaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NumeroDaParcela")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("ValorDaParcela")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("DividaId");

                    b.ToTable("Parcelas", (string)null);
                });

            modelBuilder.Entity("ControleDeDividas.Domain.Models.Parcela", b =>
                {
                    b.HasOne("ControleDeDividas.Domain.Models.Divida", "Divida")
                        .WithMany("Parcelas")
                        .HasForeignKey("DividaId")
                        .IsRequired();

                    b.Navigation("Divida");
                });

            modelBuilder.Entity("ControleDeDividas.Domain.Models.Divida", b =>
                {
                    b.Navigation("Parcelas");
                });
#pragma warning restore 612, 618
        }
    }
}
